# Generated by Django 2.0.7 on 2018-07-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
