# Generated by Django 2.1.1 on 2018-09-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_auto_20180920_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_completed',
            field=models.DateTimeField(blank=True),
        ),
    ]
