# Generated by Django 2.1.1 on 2018-09-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20180928_0138'),
        ('board', '0005_auto_20180929_2152'),
    ]

    operations = [
    ]
