# Generated by Django 2.1.1 on 2018-09-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_note_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='user',
        ),
    ]
